### ISSUE TITLE
revisement request

### ISSUE THREAD

**Issue by gnawcire** [joeangel/25122487-qingming#1]
圖我都改好了，丟了檔案給你(25122487-qingming-gh-pages-revisement20160301211530.zip)。
請協助調整以下功能，括號是ppt說明的對應頁面：
1. 取zip內img資料夾覆蓋原有內容
2. (p1)祈福卡活動說明--->祈福卡&集章趣，內文刪減：僅留日期，其他改成圖片(img/card-small.jpg)，圖片作外連至原圖(img/card.jpg)
3. (p2)內文修改：行駛日期
4. (p3)內文刪減：刪除最後一行
5. (p4)內文刪減：刪除最後一句

**Comment by joeangel** [comment]
1. 取zip內img資料夾覆蓋原有內容
d8b6221 - Update images
7ef630c - Optimize jpg

2. (p1)祈福卡活動說明--->祈福卡&集章趣，內文刪減：僅留日期，其他改成圖片(img/card-small.jpg)，圖片作外連至原圖(img/card.jpg)
9785008 - Update design area and add image: card

3. (p2)內文修改：行駛日期
caed043 - Update traffic control date

4. (p3)內文刪減：刪除最後一行
05c1120 - Update info for park

5. (p4)內文刪減：刪除最後一句
8407042 - Update worship info
