### ISSUE TITLE
final revision

### ISSUE THREAD

**Issue by gnawcire** [joeangel/25122487-qingming#2]
1. 刪除祈福卡&集章趣頁面的文字，只留圖片(修正案未移除乾淨...補上)
2. 將所有的「行駛日期」改為以下：
行駛日期：3/19(六)、3/20(日)、3/26(六)、3/27(日)、4/2(六)~4/5(二)
3. 交通管制表格，請統一成表格的字體大小
4. 祈福卡&集章趣頁面縮圖(img/card.jpg)，刪除後拿原圖(img/card.jpg)壓縮至縮圖大小

**Comment by joeangel** [comment]
1. 刪除祈福卡&集章趣頁面的文字，只留圖片(修正案未移除乾淨...補上)
8fd60ef - Remove a sentence for design-box

2. 將所有的「行駛日期」改為以下： 行駛日期：3/19(六)、3/20(日)、3/26(六)、3/27(日)、4/2(六)~4/5(二)
38e8a84 - Update traffic date

3. 交通管制表格，請統一成表格的字體大小
737ebb0 - Let iframe table font-size same as body
7760d69 - Set iframe font-size from 9px to 16px

4. 祈福卡&集章趣頁面縮圖(img/card.jpg)，刪除後拿原圖(img/card.jpg)壓縮至縮圖大小
dbfe105 - Update card-small.jpg
